import { useEffect, useRef, useState } from "react";
import { updatePlannedDeadlines } from "../../lib/supabaseData.ts";
import { DEADLINE_KEYS, PROTECTED_KEYS, createPlannedDeadlineCoordinator, plannedSnapshot, protectedSnapshot, resultMessage, validatePlannedDeadlineDraft } from "./plannedDeadlineEditModel.ts";
import type { Activity } from "../../types/domain.ts";

export default function PlannedDeadlineDialog({ a, onClose, onReload }: { a:Activity; onClose:()=>void; onReload:()=>void }) {
  const before=plannedSnapshot(a); const protectedValues=protectedSnapshot(a); const [draft,setDraft]=useState(before); const [reason,setReason]=useState(""); const [confirmed,setConfirmed]=useState(false); const [error,setError]=useState(""); const [conflict,setConflict]=useState(false); const [busy,setBusy]=useState(false); const lock=useRef(createPlannedDeadlineCoordinator()); const first=useRef<HTMLHeadingElement>(null);
  useEffect(()=>{first.current?.focus(); const escape=(e:KeyboardEvent)=>{if(e.key==="Escape"){e.preventDefault();if(!lock.current.isBusy())onClose();}};window.addEventListener("keydown",escape);return()=>window.removeEventListener("keydown",escape)},[onClose]);
  const save=async()=>{const local=validatePlannedDeadlineDraft(before,draft,reason,confirmed,a.version);if(local){setError(local);return;}setBusy(true);try{const r=await lock.current.run(()=>updatePlannedDeadlines({validationCode:a.code,deadlines:draft,reason,expectedVersion:a.version!,confirmed}));if(!r)return;if(r.ok){onClose();onReload();return;}setError(resultMessage(r));setConflict(r.error_code==="VERSION_CONFLICT");}catch(e){setError(e instanceof Error?e.message:String(e));}finally{setBusy(false)}};
  return <div className="planned-deadline-backdrop" role="presentation"><section className="planned-deadline-dialog" data-planned-deadline-dialog role="dialog" aria-modal="true" aria-labelledby="planned-deadline-title"><h2 ref={first} tabIndex={-1} id="planned-deadline-title">Chỉnh kế hoạch thủ công</h2><p data-planned-deadline-identity>{a.code}</p><p data-planned-deadline-version>Phiên bản: {a.version ?? "—"}</p><div className="planned-deadline-grid">{DEADLINE_KEYS.map(k=><label key={k}>{k}<span>Đã tải: {before[k]||"—"}</span><input data-planned-deadline-input={k} type="date" value={draft[k]||""} disabled={busy} onChange={e=>setDraft(x=>({...x,[k]:e.target.value||null}))}/></label>)}</div><h3>Ngày thực tế và trạng thái được bảo vệ</h3><div className="planned-deadline-protected">{PROTECTED_KEYS.map(k=><p key={k} data-planned-deadline-protected={k}>{k}: <b>{protectedValues[k]||"—"}</b></p>)}</div><label>Lý do<input aria-label="Lý do chỉnh deadline kế hoạch" value={reason} disabled={busy} onChange={e=>setReason(e.target.value)}/></label><label><input data-planned-deadline-confirmation type="checkbox" checked={confirmed} disabled={busy} onChange={e=>setConfirmed(e.target.checked)}/>Tôi xác nhận chỉ đổi bốn deadline kế hoạch; ngày thực tế, trạng thái, người thực hiện và mã hạng mục giữ nguyên.</label>{error&&<p data-planned-deadline-error role="alert">{error}</p>}{conflict&&<button data-planned-deadline-reload type="button" disabled={busy} onClick={()=>{onClose();onReload();}}>Tải lại hạng mục</button>}<div><button type="button" disabled={busy} onClick={onClose}>Đóng</button><button data-planned-deadline-submit type="button" disabled={busy} onClick={()=>void save()}>Lưu</button></div></section></div>;
}
