import type { Activity } from "../../types/domain.ts";
export const DEADLINE_KEYS=["deadline_protocol","deadline_validation","deadline_report","deadline_vmp"] as const; export type PlannedDeadlineKey=typeof DEADLINE_KEYS[number]; export type PlannedDeadlineSnapshot=Record<PlannedDeadlineKey,string|null>;
export const PROTECTED_KEYS=["actual_protocol_date","actual_validation_date","actual_report_date","actual_vmp_date","status_protocol","status_validation","status_report","status_vmp"] as const; export type ProtectedKey=typeof PROTECTED_KEYS[number]; export type ProtectedSnapshot=Record<ProtectedKey,string|null>;
export type PlannedDeadlineErrorCode="ACCOUNT_DISABLED"|"ROLE_UNRESOLVED"|"FORBIDDEN"|"INVALID_DEADLINE_PAYLOAD"|"EXPECTED_REVISION_REQUIRED"|"REASON_REQUIRED"|"CONFIRMATION_REQUIRED"|"ITEM_NOT_FOUND"|"ITEM_STATE_INACTIVE"|"VERSION_CONFLICT"|"DEADLINE_ERASURE_FORBIDDEN"|"DEADLINE_ORDER_INVALID"|"NO_ACTIONABLE_CHANGE"|"WRITE_MISMATCH";
export type PlannedDeadlineResult={ok:true;validation_code:string;old_deadlines:PlannedDeadlineSnapshot;new_deadlines:PlannedDeadlineSnapshot;changed_fields:PlannedDeadlineKey[];previous_version:number;current_version:number;actor_id:string|null;effective_role:"admin"|"qa_manager"|"service_role";reason:string;protected_fields_preserved:true}|{ok:false;error_code:PlannedDeadlineErrorCode;error:string;validation_code?:string;expected_version?:number;current_version?:number;requires_reload?:true};
const raw=(a:Activity)=>(a._raw||{}) as Record<string,unknown>;const text=(v:unknown)=>typeof v==="string"&&v.trim()?v.trim():null;
export const canPresentPlannedDeadlineEdit=(enabled:unknown,role:unknown)=>enabled==="true"&&(role==="admin"||role==="qa_manager");
export function plannedSnapshot(a:Activity):PlannedDeadlineSnapshot{const r=raw(a);return{deadline_protocol:text(a.dlProtocol??r.deadline_protocol??r.dl_de_cuong),deadline_validation:text(a.dlValidation??r.deadline_validation??r.dl_tham_dinh),deadline_report:text(a.dlReport??r.deadline_report??r.dl_bao_cao),deadline_vmp:text(a.dlVmp??r.deadline_vmp??r.dl_vmp)}}
export function protectedSnapshot(a:Activity):ProtectedSnapshot{const r=raw(a);return{actual_protocol_date:text(a.actProtocol??r.actual_protocol_date??r.ngay_de_cuong),actual_validation_date:text(a.actValidation??r.actual_validation_date??r.ngay_tham_dinh),actual_report_date:text(a.actReport??r.actual_report_date??r.ngay_bao_cao),actual_vmp_date:text(a.actVmp??r.actual_vmp_date??r.ngay_vmp),status_protocol:text(r.status_protocol??r.tt_de_cuong),status_validation:text(r.status_validation??r.tt_tham_dinh),status_report:text(r.status_report??r.tt_bao_cao),status_vmp:text(r.status_vmp??r.tt_vmp)}}
export function validatePlannedDeadlineDraft(before:PlannedDeadlineSnapshot,next:PlannedDeadlineSnapshot,reason:string,confirmed:boolean,version:unknown):string|null{if(!Number.isFinite(version)||!Number.isInteger(version)||Number(version)<0)return"Thiếu phiên bản hạng mục đã tải";if(!reason.trim())return"Phải nhập lý do điều chỉnh deadline kế hoạch";if(!confirmed)return"Phải xác nhận chỉ đổi bốn deadline kế hoạch";if(DEADLINE_KEYS.some(k=>next[k]!==null&&!/^\d{4}-\d{2}-\d{2}$/.test(next[k]!)))return"Deadline phải là ngày ISO YYYY-MM-DD hoặc null";if(DEADLINE_KEYS.some(k=>before[k]!==null&&next[k]===null))return"Không được xoá deadline kế hoạch đã có";const d=DEADLINE_KEYS.map(k=>next[k]).filter((x):x is string=>!!x);if(d.some((x,i)=>i&&d[i-1]>x))return"Bốn deadline kế hoạch phải theo đúng thứ tự";if(DEADLINE_KEYS.every(k=>before[k]===next[k]))return"Không có deadline nào thay đổi";return null}
export const resultMessage=(r:PlannedDeadlineResult)=>!r.ok&&r.error_code==="VERSION_CONFLICT"?`${r.error} (phiên bản đã tải ${r.expected_version}; hiện tại ${r.current_version})`:!r.ok?r.error:"";
export function createPlannedDeadlineCoordinator(){let busy=false;return{isBusy:()=>busy,async run<T>(work:()=>Promise<T>):Promise<T|null>{if(busy)return null;busy=true;try{return await work()}finally{busy=false}}}}
