import type { Activity } from "../../types/domain.ts";
export type PlannedDeadlineKey = "deadline_protocol" | "deadline_validation" | "deadline_report" | "deadline_vmp";
export type PlannedDeadlineSnapshot = Record<PlannedDeadlineKey, string | null>;
export type PlannedDeadlineErrorCode = "ACCOUNT_DISABLED"|"ROLE_UNRESOLVED"|"FORBIDDEN"|"INVALID_DEADLINE_PAYLOAD"|"EXPECTED_REVISION_REQUIRED"|"REASON_REQUIRED"|"CONFIRMATION_REQUIRED"|"ITEM_NOT_FOUND"|"ITEM_STATE_INACTIVE"|"VERSION_CONFLICT"|"DEADLINE_ERASURE_FORBIDDEN"|"DEADLINE_ORDER_INVALID"|"NO_ACTIONABLE_CHANGE"|"WRITE_MISMATCH";
export type PlannedDeadlineResult = { ok:true; validation_code:string; old_deadlines:PlannedDeadlineSnapshot; new_deadlines:PlannedDeadlineSnapshot; changed_fields:PlannedDeadlineKey[]; previous_version:number; current_version:number; actor_id:string|null; effective_role:"admin"|"qa_manager"|"service_role"; reason:string; protected_fields_preserved:true } | { ok:false; error_code:PlannedDeadlineErrorCode; error:string; validation_code?:string; expected_version?:number; current_version?:number; requires_reload?:true };
export const canPresentPlannedDeadlineEdit=(enabled: unknown, role: unknown)=>enabled === "true" && (role === "admin" || role === "qa_manager");
const raw=(a:Activity)=>(a._raw||{}) as Record<string,unknown>; const val=(v:unknown)=>typeof v === "string"&&v.trim()?v.trim():null;
export function plannedSnapshot(a:Activity): PlannedDeadlineSnapshot { const r=raw(a); return { deadline_protocol:val(a.dlProtocol??r.deadline_protocol??r.dl_de_cuong), deadline_validation:val(a.dlValidation??r.deadline_validation??r.dl_tham_dinh), deadline_report:val(a.dlReport??r.deadline_report??r.dl_bao_cao), deadline_vmp:val(a.dlVmp??r.deadline_vmp??r.dl_vmp) }; }
export function validatePlannedDeadlineDraft(before:PlannedDeadlineSnapshot,next:PlannedDeadlineSnapshot,reason:string,confirmed:boolean):string|null { if(!reason.trim()) return "Phải nhập lý do điều chỉnh deadline kế hoạch"; if(!confirmed) return "Phải xác nhận chỉ đổi bốn deadline kế hoạch"; const xs=Object.values(next); if(xs.some(x=>x!==null&&!/^\d{4}-\d{2}-\d{2}$/.test(x))) return "Deadline phải là ngày ISO YYYY-MM-DD hoặc null"; const keys=Object.keys(before) as PlannedDeadlineKey[]; if(keys.some(k=>before[k]!==null&&next[k]===null)) return "Không được xoá deadline kế hoạch đã có"; const ordered=xs.filter((x):x is string=>!!x); if(ordered.some((x,i)=>i&&ordered[i-1]>x)) return "Bốn deadline kế hoạch phải theo đúng thứ tự"; if(keys.every(k=>before[k]===next[k])) return "Không có deadline nào thay đổi"; return null; }
export function createPlannedDeadlineCoordinator(){let busy=false;return {isBusy:()=>busy,async run<T>(work:()=>Promise<T>):Promise<T|null>{if(busy)return null;busy=true;try{return await work();}finally{busy=false;}}};}
